spring.application.name=Lc-Loan-Manajement-System

# database configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.hibernate.ddl-auto=update

# JWT configuration
app.jwt-secret=${JWT_SECRET}
app.jwt-expiration-ms=${JWT_EXPIRATION}

# Swagger/OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.csrf.enabled=false

# ResClient
api.lms.base-url = https://leptosomic-unransomed-anisha.ngrok-free.dev